Stat svc
TerentevOleg/java-explore-with-me pull request #2
Opened 2023-02-28 19:46 UTC by TerentevOleg

2023-03-02 13:29 UTC, alexache requested changes

2023-03-02 13:29 UTC, alexache commented on main-service/pom.xml
> +			<version>0.0.1-SNAPSHOT</version>
Лучше указывать  ${project.version} для зависимостей на свои же модули

2023-03-02 13:29 UTC, alexache commented on stats/stats-client/pom.xml
> +    <version>0.0.1-SNAPSHOT</version>
зачем это дублировать? это уже есть в родительском модуле

2023-03-02 13:29 UTC, alexache commented on stats/stats-client/src/main/java/ru/practicum/statsclient/StatsClient.java
> +    public ResponseEntity<Object> get(String start, String end, List<String> uris, Boolean unique) {
С Object, пожалуй, будет неудобно работать, может лучше List<StatsDtoOut>?

2023-03-02 13:29 UTC, alexache commented on stats/stats-server/pom.xml
> +				<version>3.10.1</version>
Версии библиотек и плагинов должны быть в родительском модуле

2023-03-02 18:13 UTC, TerentevOleg commented on stats/stats-client/pom.xml
> +    <version>0.0.1-SNAPSHOT</version>
Исправлено в модуле stats-dto и stats-client.

2023-03-02 18:20 UTC, TerentevOleg commented on main-service/pom.xml
> +			<version>0.0.1-SNAPSHOT</version>
Исправлено.

2023-03-02 18:38 UTC, TerentevOleg commented on stats/stats-server/pom.xml
> +				<version>3.10.1</version>
Вынесено в родительский модуль.

2023-03-02 19:47 UTC, TerentevOleg commented on stats/stats-client/src/main/java/ru/practicum/statsclient/StatsClient.java
> +    public ResponseEntity<Object> get(String start, String end, List<String> uris, Boolean unique) {
Попробовал переделать в базовом классе через дженерики, не увеличивая количество методов.

2023-03-03 17:59 UTC, alexache approved these changes

2023-03-03 21:42 UTC, merged