Stage 2 for review
TerentevOleg/java-explore-with-me pull request #3
Opened 2023-03-12 16:03 UTC by TerentevOleg

2023-03-14 00:11 UTC, alexache requested changes

2023-03-14 00:11 UTC, alexache commented on main-service/src/main/java/ru/practicum/mainservice/category/controller/CategoryAdminController.java
> +    public ResponseEntity<CategoryDtoOut> add(@RequestBody @Valid CategoryDtoIn categoryDtoIn) {
(опционально) действительно ли нужны все эти ResponseEntity

2023-03-14 00:11 UTC, alexache commented on main-service/pom.xml
> +				<version>1.1.3</version>
Версии плагинов должны быть указаны в родительском модуле

2023-03-14 00:11 UTC, alexache commented on main-service/src/main/java/ru/practicum/mainservice/category/dto/CategoryDtoIn.java
> +    String name;
Пропущены модификаторы доступа

2023-03-14 00:11 UTC, alexache commented on main-service/src/main/java/ru/practicum/mainservice/compilation/model/Compilation.java
> +        return Objects.hash(id);
В разных моделях разная реализация метода хешкода, это специально?

2023-03-14 00:11 UTC, alexache commented on main-service/src/main/java/ru/practicum/mainservice/event/model/Event.java
> +    private Long confirmedRequests;
Это не нужно хранить как поле у события - его нужно подсчитывать запросом к таблице с заявками

2023-03-14 00:11 UTC, alexache commented on main-service/src/main/java/ru/practicum/mainservice/event/model/Event.java
> +    private Long views;
Это поле не должно храниться модели события  - нужно запрашивать количество просмотров у сервера статистики

2023-03-14 00:11 UTC, alexache commented on main-service/src/main/java/ru/practicum/mainservice/event/service/EventServiceImpl.java
> +        list.forEach(this::setConfirmedRequests);
Не должно быть запросов к базе в цикле

2023-03-14 00:11 UTC, alexache commented on main-service/src/main/java/ru/practicum/mainservice/event/service/EventServiceImpl.java
> +        statsClient.get(startDate, endDate, Collections.singletonList("/events"), false);
Где получение статистики для событий из результирующего списка?

2023-03-14 00:11 UTC, alexache commented on main-service/src/main/java/ru/practicum/mainservice/request/service/RequestServiceImpl.java
> +            if ("CONFIRMED".equals(updateRequest.getStatus())) {
Не может ли быть превышен лимит на количество заявок уже в данном цикле?

2023-03-14 00:11 UTC, alexache commented on main-service/src/main/java/ru/practicum/mainservice/user/service/UserService.java
> +    List<UserDtoOut> getAll(ArrayList<Long> ids, Integer from, Integer size);
Для чего отсылка к конкретной имплементации листа?

2023-03-14 10:03 UTC, TerentevOleg commented on main-service/pom.xml
> +				<version>1.1.3</version>
Исправлено.

2023-03-14 10:03 UTC, TerentevOleg commented on main-service/src/main/java/ru/practicum/mainservice/category/dto/CategoryDtoIn.java
> +    String name;
Исправлено.

2023-03-14 10:10 UTC, TerentevOleg commented on main-service/src/main/java/ru/practicum/mainservice/compilation/model/Compilation.java
> +        return Objects.hash(id);
Не специально. Это я генерировал автоматически не верно. Исправил.

2023-03-14 10:15 UTC, TerentevOleg commented on main-service/src/main/java/ru/practicum/mainservice/user/service/UserService.java
> +    List<UserDtoOut> getAll(ArrayList<Long> ids, Integer from, Integer size);
Исправлено.

2023-03-14 11:24 UTC, TerentevOleg commented on main-service/src/main/java/ru/practicum/mainservice/request/service/RequestServiceImpl.java
> +            if ("CONFIRMED".equals(updateRequest.getStatus())) {
Нет, не может. Лимит на количество заявок проверяется перед циклом, в этой строчке кода: event.getParticipantLimit() <= requestRepository.countRequestByEventIdAndStatus. Если лимит на количество заявок уже достигнут, то исключение будет брошено. Так же сделал switch вместо for для более легкого чтения кода.

2023-03-14 12:26 UTC, TerentevOleg commented on main-service/src/main/java/ru/practicum/mainservice/event/service/EventServiceImpl.java
> +        list.forEach(this::setConfirmedRequests);
Исправлено.

2023-03-14 14:29 UTC, alexache commented on main-service/src/main/java/ru/practicum/mainservice/request/service/RequestServiceImpl.java
> +            if ("CONFIRMED".equals(updateRequest.getStatus())) {
Так а на вход разве не множество заявок?

2023-03-14 15:11 UTC, TerentevOleg commented on main-service/src/main/java/ru/practicum/mainservice/event/model/Event.java
> +    private Long confirmedRequests;
Исправлено, добавлен метод countConfirmedRequestsByEventId в RequestRepository.

2023-03-14 16:25 UTC, TerentevOleg commented on main-service/src/main/java/ru/practicum/mainservice/event/model/Event.java
> +    private Long views;
Исправлено.

2023-03-14 17:03 UTC, TerentevOleg commented on main-service/src/main/java/ru/practicum/mainservice/event/service/EventServiceImpl.java
> +        statsClient.get(startDate, endDate, Collections.singletonList("/events"), false);
Исправлено.

2023-03-14 19:17 UTC, TerentevOleg commented on main-service/src/main/java/ru/practicum/mainservice/request/service/RequestServiceImpl.java
> +            if ("CONFIRMED".equals(updateRequest.getStatus())) {
Добавил доп проверку.

2023-03-15 14:47 UTC, alexache requested changes

2023-03-15 14:47 UTC, alexache commented on main-service/src/main/java/ru/practicum/mainservice/event/model/Event.java
> +        return getClass().hashCode();
(на будущее) Objects.hash(id) выглядел удачнее с точки зрения корректности работы с JPA моделями

2023-03-15 14:47 UTC, alexache commented on main-service/src/main/java/ru/practicum/mainservice/event/service/EventServiceImpl.java
> +        //event.setViews(0L);
Закомментированный код нужно удалять

2023-03-15 14:47 UTC, alexache commented on main-service/src/main/java/ru/practicum/mainservice/event/service/EventServiceImpl.java
> +            ResponseEntity<List> response = statsClient.get(startDate, endDate,
Это запрос ко внешнему сервису в цикле, а нужен 1 запрос по всему списку событий

2023-03-15 14:47 UTC, alexache commented on main-service/src/main/java/ru/practicum/mainservice/event/service/EventServiceImpl.java
> +        requestRepository.countConfirmedRequestsByEventId(event.getId());
Что этот метод теперь делает?

2023-03-15 14:47 UTC, alexache commented on main-service/src/main/java/ru/practicum/mainservice/event/service/EventServiceImpl.java
> +        //event.setViews(0L);
И еще выше - setConfirmedRequest  - что он может считать, если событие только создается? Откуда могут быть запросы?

2023-03-15 14:47 UTC, alexache commented on main-service/src/main/java/ru/practicum/mainservice/event/service/EventServiceImpl.java
> +            eventViewsList.add(new EventViewsDtoOut(event, views));
Разве такую же логику не требуется добавить в другие методы получения списка событий, админом например?

2023-03-15 14:47 UTC, alexache commented on main-service/src/main/java/ru/practicum/mainservice/event/service/EventServiceImpl.java
> +        return sortedEventViewsList.stream()
Еще не вижу выставления количества подтвержденных заявок

2023-03-15 14:47 UTC, alexache commented on main-service/src/main/java/ru/practicum/mainservice/request/repository/RequestRepository.java
> +    @Query("SELECT COUNT(r) " +
(опционально) можно и через именования метода сделать такой запрос

2023-03-15 14:47 UTC, alexache commented on main-service/src/main/java/ru/practicum/mainservice/request/service/RequestServiceImpl.java
> +        if (event.getParticipantLimit() < requests.size()) {
Мне кажется, условие должно быть немного сложнее. нужно смотреть на количество оставшихся мест, и лучше внутри цикла отслеживать

2023-03-15 14:47 UTC, alexache commented on main-service/src/main/java/ru/practicum/mainservice/request/service/RequestServiceImpl.java
> +        switch (updateRequest.getStatus()) {
Хорошо бы разделить обработку подтверждения и отклонения в разные методы, логика немного разная. Почему не разрешать отклонения заявок, если количество подтвержденных достигло лимита?

2023-03-15 14:47 UTC, alexache commented on main-service/src/main/java/ru/practicum/mainservice/request/service/RequestServiceImpl.java
> +                    requestRepository.saveAndFlush(request);
Это запросы к базе в цикле, что плохо. Лучше сначала у всего списка поменять статус соответствующе 
К тому же можно достигнуть лимита подтвержденных заявок в списке, Нужно будет часть подтвердить, а оставшиеся отклонить

2023-03-15 14:47 UTC, alexache commented on main-service/src/main/resources/schema.sql
> -    confirmed_requests BIGINT,
Еще и views надо удалить

2023-03-15 16:19 UTC, TerentevOleg commented on main-service/src/main/java/ru/practicum/mainservice/event/model/Event.java
> +        return getClass().hashCode();
Сразу исправил все хешкоды на Objects.hash(id)

2023-03-15 16:23 UTC, TerentevOleg commented on main-service/src/main/java/ru/practicum/mainservice/event/service/EventServiceImpl.java
> +        //event.setViews(0L);
Исправлено. Удалил неиспользуемый код.

2023-03-15 16:36 UTC, TerentevOleg commented on main-service/src/main/java/ru/practicum/mainservice/event/service/EventServiceImpl.java
> +        //event.setViews(0L);
Исправлено. Удалил, запросов быть не может.

2023-03-15 16:37 UTC, TerentevOleg commented on main-service/src/main/java/ru/practicum/mainservice/event/service/EventServiceImpl.java
> +        requestRepository.countConfirmedRequestsByEventId(event.getId());
Исправлено. Удалил неиспользуемый метод.

2023-03-15 16:42 UTC, TerentevOleg commented on main-service/src/main/resources/schema.sql
> -    confirmed_requests BIGINT,
Исправлено. Лишнее удалено.

2023-03-15 17:10 UTC, TerentevOleg commented on main-service/src/main/java/ru/practicum/mainservice/event/service/EventServiceImpl.java
> +            ResponseEntity<List> response = statsClient.get(startDate, endDate,
Исправлено. Сделан 1 запрос к внешнему сервису.

2023-03-16 11:38 UTC, TerentevOleg commented on main-service/src/main/java/ru/practicum/mainservice/request/service/RequestServiceImpl.java
> +        switch (updateRequest.getStatus()) {
Исправлено. Добавил два приватных метода confirmRequests и rejectRequests.

2023-03-16 11:39 UTC, TerentevOleg commented on main-service/src/main/java/ru/practicum/mainservice/request/service/RequestServiceImpl.java
> +        if (event.getParticipantLimit() < requests.size()) {
Исправлено. Подтверждение и отклонение заявок теперь обрабатываются в одном цикле. Внутри цикла  проверяется, можно ли подтвердить заявку или нет, и обрабатывается соответствующим образом.

2023-03-16 11:40 UTC, TerentevOleg commented on main-service/src/main/java/ru/practicum/mainservice/request/service/RequestServiceImpl.java
> +                    requestRepository.saveAndFlush(request);
Исправлено. Проверка лимита участников осуществляется до того, как будут получены заявки. Это позволяет избежать необходимости выполнять дополнительный запрос к БД, если лимит уже достигнут. Все заявки сохраняются в БД одним вызовом метода saveAll, вместо вызова save в цикле.

2023-03-16 14:30 UTC, TerentevOleg commented on main-service/src/main/java/ru/practicum/mainservice/event/service/EventServiceImpl.java
> +        return sortedEventViewsList.stream()
Исправлено.

2023-03-16 17:21 UTC, TerentevOleg commented on main-service/src/main/java/ru/practicum/mainservice/event/service/EventServiceImpl.java
> +            eventViewsList.add(new EventViewsDtoOut(event, views));
Исправлено. Добавил логику с просмотрами в другие методы.

2023-03-17 19:07 UTC, alexache requested changes

2023-03-17 19:07 UTC, alexache commented on main-service/src/main/java/ru/practicum/mainservice/event/service/EventServiceImpl.java
> +                            .countConfirmedRequestsByEventId(ev.getEvent().getId()));
Это снова запрос к базе в цикле

2023-03-17 19:07 UTC, alexache commented on main-service/src/main/java/ru/practicum/mainservice/event/service/EventServiceImpl.java
> +                            .countConfirmedRequestsByEventId(ev.getEvent().getId()));
И это в цикле

2023-03-17 19:07 UTC, alexache commented on main-service/src/main/java/ru/practicum/mainservice/event/service/EventServiceImpl.java
> +                            .countConfirmedRequestsByEventId(ev.getEvent().getId()));
И это в  цикле

2023-03-17 22:12 UTC, TerentevOleg commented on main-service/src/main/java/ru/practicum/mainservice/event/service/EventServiceImpl.java
> +                            .countConfirmedRequestsByEventId(ev.getEvent().getId()));
Все исправлено. В репозиторий добавлен метод countConfirmedRequestsByEventIds. Теперь confirmedRequestsMap получает количество подтвержденных заявок для каждого ивента с помощью batch-запроса в методе countConfirmedRequestsByEventIds.

2023-03-18 20:14 UTC, alexache approved these changes

2023-03-18 21:04 UTC, merged