3 stage for review
TerentevOleg/java-explore-with-me pull request #4
Opened 2023-03-21 10:53 UTC by TerentevOleg

2023-03-22 15:12 UTC, alexache requested changes

2023-03-22 15:12 UTC, alexache commented on postman/feature.json
> +      "request": {
Я бы добавил немного больше кейсов - добавление комментария от юзера на событие, которое он не посещал, например. Попытка изменения или удаления не своего комментария

2023-03-22 15:12 UTC, alexache commented on main-service/src/main/java/ru/practicum/mainservice/comment/service/CommentServiceImpl.java
> +        if (!event.getState().equals(State.PUBLISHED)) {
Будет логично еще проверять, что данный пользователь ходил на это событие через список подтвержденных заявок

2023-03-22 15:12 UTC, alexache commented on main-service/src/main/java/ru/practicum/mainservice/comment/service/CommentServiceImpl.java
> +        if (Objects.isNull(rangeStart) && Objects.isNull(rangeEnd)) {
(опционально) Наверное это можно сделать с помощию дефолтных значений в контроллере?

2023-03-22 15:12 UTC, alexache commented on main-service/src/main/java/ru/practicum/mainservice/comment/service/CommentServiceImpl.java
> +        } else comment.setState(CommentStatus.CANCELED);
По код стилю лучше бы добавить еще блок с { } в else

2023-03-22 15:12 UTC, alexache commented on main-service/src/main/java/ru/practicum/mainservice/event/service/EventServiceImpl.java
> +                    eventDtoOut.setComments(getCommentDtoOutList(ev.getEvent()));
Это запрос к базе в цикле - так нельзя, нужно переделать на поулчение комментариев по списку событий

2023-03-22 19:34 UTC, TerentevOleg commented on main-service/src/main/java/ru/practicum/mainservice/event/service/EventServiceImpl.java
> +                    eventDtoOut.setComments(getCommentDtoOutList(ev.getEvent()));
Исправлено. Добавлен метод getCommentDtoOutMap.

2023-03-22 19:34 UTC, TerentevOleg commented on main-service/src/main/java/ru/practicum/mainservice/comment/service/CommentServiceImpl.java
> +        } else comment.setState(CommentStatus.CANCELED);
Исправлено.

2023-03-22 21:17 UTC, TerentevOleg commented on main-service/src/main/java/ru/practicum/mainservice/comment/service/CommentServiceImpl.java
> +        if (Objects.isNull(rangeStart) && Objects.isNull(rangeEnd)) {
Исправлено.

2023-03-23 17:12 UTC, TerentevOleg commented on postman/feature.json
> +      "request": {
Исправлено. Добавлены новые тесты.

2023-03-23 17:12 UTC, TerentevOleg commented on main-service/src/main/java/ru/practicum/mainservice/comment/service/CommentServiceImpl.java
> +        if (!event.getState().equals(State.PUBLISHED)) {
Исправлено. Добавлена проверка на то, что пользователь ходил на событие.

2023-03-24 19:10 UTC, alexache approved these changes

2023-03-24 21:22 UTC, merged